#!/bin/bash

# name		icon
# light		
SCRIPTS="$HOME/Repos/github.com/mrbooshehri/dot/scripts"
light=$(light -G | cut -d '.' -f 1)
icon=""

"$SCRIPTS/dunst/notify-send" -t 900 -r  "$(pgrep -x dunst)" "$icon  $light"

