#!/bin/bash
SCRIPTS=/home/mhmd/Repos/github.com/mrbooshehri/dot/scripts

vol=$(pamixer --get-volume)
mute=$(pamixer --get-mute)
icon=""

[[ "$mute" != "false" ]] && icon=""
$SCRIPTS/dunst/notify-send -r "$(pgrep -x dunst)" "$icon  $vol"

