#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f -D 6 &
pgerp -x conky > /dev/null || conky > /dev/null 2>&1 &
pgerp -x redshift > /dev/null || redshift -c ~/.config/redshift/redshift.conf > /dev/null 2>&1 &

killall -q polybar > /dev/null  
polybar bspwm &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-fill --randomize /mnt/1TB/Pictures/Wallpaper.repo/*

# set layout
setxkbmap -layout us,ir 
setxkbmap -option 'grp:alt_shift_toggle' 

wmname LG3D

bspc monitor -d I II III IV V VI 



bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a SpeedCrunch state=floating
bspc rule -a VirtualBox Manager state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Tor Browser desktop='^5'
bspc rule -a TelegramDesktop desktop='^6'

nm-applet &
blueman-applet &
pywalfox start &
safeeyes &
syncthing &
