#!/bin/bash
#                _                     _          _          _ 
#               | |                   | |        | |        (_)
# _ __ ___  _ __| |__   ___   ___  ___| |__   ___| |__  _ __ _ 
#| '_ ` _ \| '__| '_ \ / _ \ / _ \/ __| '_ \ / _ \ '_ \| '__| |
#| | | | | | |  | |_) | (_) | (_) \__ \ | | |  __/ | | | |  | |
#|_| |_| |_|_|  |_.__/ \___/ \___/|___/_| |_|\___|_| |_|_|  |_|

ARR=()
ARR+=("Dictionary")
#ARR+=("Colorscheme")
ARR+=("Pirokit")
ARR+=("Ytfzf")
ARR+=("Lyrics")
ARR+=("Mitype")
ARR+=("Redyt")
ARR+=("dradio")
ARR+=("Ambiant Music")
ARR+=("OBS-remote")
ARR+=("Reddit-wall")
ARR+=("Wallhaven-wall")
ARR+=("Change-wall")
ARR+=("Jupyter Lab")
ARR+=("Passgen")
ARR+=("Usergen")

CHOICE=$(printf '%s\n' "${ARR[@]}" | dmenu)

case $CHOICE in
  "Dictionary") dmenu-dict ;;
#  "Colorscheme") dmenu-wal-colorscheme ;;
  "Pirokit") $GHREPOS/pirokit/pirokit ;;
  "Ytfzf") $GHREPOS/ytfzf/ytfzf -D ;;
  "Lyrics") dmenu-lyrics;;
  "Mitype") type-test;;
  "Redyt") $GHREPOS/redyt/redyt ;;
  "dradio") dradio -d ;;
  "Ambiant Music") dmenu-ambiant-music ;;
  "obs-remote") dmenu-obs ;;
  "Reddit-wall") waldl ;;
  "Wallhaven-wall") dmenu-wallget ;;
  "Change-wall") dmenu-wal-change ;;
  "Jupyter Lab") dmenu-jupyter-notebook ;;
  "Passgen")
    ~/Projects/python/pass_generator/passgen.py -c 
    notify-send "Passgen" "Password copied in your clipboard"
    ;;
  "Usergen")
    genuname -n | xsel -bi
    notify-send "Genunam" "Username copied in your clipboard"
    ;;
esac
