#!/bin/bash
#                _                     _          _          _ 
#               | |                   | |        | |        (_)
# _ __ ___  _ __| |__   ___   ___  ___| |__   ___| |__  _ __ _ 
#| '_ ` _ \| '__| '_ \ / _ \ / _ \/ __| '_ \ / _ \ '_ \| '__| |
#| | | | | | |  | |_) | (_) | (_) \__ \ | | |  __/ | | | |  | |
#|_| |_| |_|_|  |_.__/ \___/ \___/|___/_| |_|\___|_| |_|_|  |_|

ARR=()
ARR+=("Dictionary")
#ARR+=("Colorscheme")
ARR+=("Pirokit")
ARR+=("Ytfzf")
ARR+=("Lyrics")
ARR+=("Mitype")
ARR+=("Redyt")
ARR+=("dradio")
ARR+=("Ambiant Music")
ARR+=("OBS-remote")
ARR+=("Reddit-wall")
ARR+=("Wallhaven-wall")
ARR+=("Change-wall")
ARR+=("Jupyter Lab")
ARR+=("Passgen")
ARR+=("Usergen")

CHOICE=$(printf '%s\n' "${ARR[@]}" | dmenu)

case $CHOICE in
  "Dictionary")
    $SCRIPTS/dmenu/dmenu-dict.sh ;;
#  "Colorscheme")
#    $SCRIPTS/dmenu/dmenu-wal-colorscheme.sh ;;
  "Pirokit")
    $GHREPOS/pirokit/pirokit ;;
  "Ytfzf")
    $GHREPOS/ytfzf/ytfzf -D ;;
  "Lyrics")
    $SCRIPTS/dmenu/dmenu-lyrics.sh;;
  "Mitype")
    $SCRIPTS/general/type-test.sh;;
  "Redyt")
    $GHREPOS/redyt/redyt ;;
  "dradio")
    dradio -d ;;
  "Ambiant Music")
    $SCRIPTS/dmenu/dmenu-ambiant-music.sh ;;
  "obs-remote")
    $SCRIPTS/dmenu/dmenu-obs.sh ;;
  "Reddit-wall")
    $SCRIPTS/general/waldl.sh ;;
  "Wallhaven-wall")
    $SCRIPTS/dmenu/dmenu-wallget.sh ;;
  "Change-wall")
    $SCRIPTS/dmenu/dmenu-wal-change.sh ;;
  "Jupyter Lab")
    $SCRIPTS/dmenu/dmenu-jupyter-notebook.sh ;;
  "Passgen")
    ~/Projects/python/pass_generator/passgen.py -c 
    notify-send "Passgen" "Password copied in your clipboard"
    ;;
  "Usergen")
    $SCRIPTS/bash/genuname.sh -n | xsel -bi
    notify-send "Genunam" "Username copied in your clipboard"
    ;;
esac
