#!/bin/bash

_startvm(){
	vboxmanage -s "${1// /\ }" --type headless
	[[ `vboxmanage list runningvms | awk -F "\"" '{print $2}'` == "$1" ]] && nority-send -t 900  "VirtualBox" "VM [ $1 ] is running." 
}
_stopvm(){
	vboxmanage controlvm "$1" poweroff
}
_listvms(){
	vboxmanage list vms | awk -F "\"" '{print $2}'
}
_vmstatus(){
	
}
_vmstatus "$*"
_stopvm "$*"
_startvm "$*"
