#!/bin/bash

VER='15.0'
URL="https://www.unicode.org/Public/emoji/${VER}/emoji-test.txt"
DIR="$HOME/.config/emofi"
FILE="$DIR/emojis.txt"

test -d $DIR || mkdir $DIR
test -f $FILE || curl $URL | grep -v '^#' | grep ' ; fully-qualified ' | cut -d'#' -f2 | awk '{$2=""; print}'> $FILE

EMOJI=`cat $FILE | rofi -dmenu -show | cut -d' ' -f1`
echo -n "$EMOJI" | xsel -bi
notify-send -t 500 -u low "Emofi" "$EMOJI copied to the clipboard."
