#!/bin/sh
test type tmux >/dev/null 2>&1 && echo "TMUX isn't installed. Skipping." && exit 1
mkdir ~/.config 2>/dev/null
rm -rf ~/.config/tmux 2>/dev/null
ln -s "$PWD" "$HOME/.config/tmux"
ls -l ~/.config/tmux 
